# Generated by Django 5.2.3 on 2025-07-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imovel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField(blank=True, null=True)),
                ('preco_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_por_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hospedes', models.PositiveIntegerField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='imovel.imovel')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'agendamento',
                'ordering': ['data_checkin'],
            },
        ),
    ]
