# Generated by Django 5.2.3 on 2025-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='link',
            field=models.URLField(default=1, max_length=1024, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
